# Generated by Django 3.2.25 on 2024-11-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='static/catalog/images/def-avatar.jpg', upload_to='static/catalog/images/')),
            ],
        ),
    ]
