# Generated by Django 5.1.3 on 2024-11-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_userprofile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
