# Generated by Django 3.2.25 on 2024-11-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_delete_signup_remove_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='def-avatar.jpg', upload_to='images/'),
        ),
    ]
